---
- #Setup
    id: 0
    name: "Setup"
    dbUser: "root"
    dbPass: "password"
    commands:
    - "echo 'Installing applications'"
#   - "apt-get update;"
#   - "apt-get install apache2 -y;"
#   - "service apache2 start;"
#   - "apt-get install sublist3r -y;"
#   - "apt-get install nmap -y;"
    - "echo 'Setting up DB'"
    - "mysql -u root '-ppassword' -e 'CREATE DATABASE chainer;' 2>/dev/null"
    - "mysql -u root '-ppassword' 'chainer' -e 'CREATE TABLE `seed` (`id` INT NOT NULL AUTO_INCREMENT,`domain` TEXT NOT NULL,PRIMARY KEY (`id`));' 2>/dev/null"
    - "mysql -u root '-ppassword' 'chainer' -e 'CREATE TABLE `subdomain` (`id` INT NOT NULL AUTO_INCREMENT,`domain` TEXT NOT NULL, `ipaddress` TEXT, PRIMARY KEY (`id`));' 2>/dev/null"
    - "mysql -u root '-ppassword' 'chainer' -e 'CREATE TABLE `ipaddressopenport` (`id` INT NOT NULL AUTO_INCREMENT,`ipaddress` TEXT NOT NULL, `port` TEXT, PRIMARY KEY (`id`));' 2>/dev/null"
 
- #Stage 1
    id: 1
    name: "Phase one scan"
    run:
    - application:
      cmd: "sublist3r -d ${INPUT}$ -n -o .sublist3rtmp 2>/dev/null"
      input: "${db.seed.domain}$"
      output:
       sourcefile: ".sublist3rtmp"
       store:
        location: "${db.subdomain.domain}$"
      cleanup:
       cmd: "rm .sublist3rtmp"
    - application:
      cmd: "${db}$"
      sql: "delete subs from subdomain as subs left join seed as seeds on subs.domain like concat('%', seeds.domain) where seeds.id is null;"
    - application:
      cmd: "nmap -sn ${INPUT}$ -oG .nmaptmp 2>/dev/null"
      input: "${db.subdomain.domain}$"
      output:
       sourcefile: ".nmaptmp"
       postoutputcmd: "cat .nmaptmp | grep Up | cut -d ' ' -f2"
       store:
        sql: "UPDATE subdomain SET ipaddress = ${RESULT}$ where domain = ${INPUT}$"
      cleanup:
       cmd: "rm .nmaptmp"
    - application:
      cmd: "${db}$"
      sql: "delete from subdomain where ipaddress is NULL;"
- #Stage 2
    id: 2
    name: "Phase 2 script scans"
    run:
    - application:
      cmd: "nmap --open --top-ports=1000 -oG .nmaptmp ${INPUT}$"
      input: ${db.subdomain.ipaddress}$
      output:
       preoutputcmd: 'for port in $(cat .nmaptmp | grep open | grep -v "#" | grep -o -P "(?<=Ports: ).*" ); do echo $port | cut -d "/" -f1,5 | grep -v -P "Ignored|State:|filtered|\(|\)" >> .ports; done'
       sourcefile: ".ports"
       store:
        sql: "INSERT INTO ipaddressopenport (id,ipaddress,port) values(null,${INPUT}$,${RESULT}$);"
      cleanup:
       cmd: "rm .ports"
